baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'UX Job Descriptions'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"
footer:
  copyright_text: 'Crafted by <a href="https://twitter.com/hannahpixels">Hannah Pixels</a> | Powered by <a href="https://github.com/avillafiorita/jekyll-datapage_gen">Jekyll Datapage Gen</a> | Theme by <a href="https://www.zerostatic.io">Zerostatic</a>'

seo:
  meta_og_title: "Jekyll Serif Theme"
  meta_og_type: "website"
  meta_og_url: "https://github.com/hannahd/uxjobdescriptions"
  meta_og_description: "A collection of User Experience job descriptions for hiring managers and UX professionals. These are NOT open positions, but give you a feeling for how roles are described at different companies."
  meta_twitter_card: "summary"
  meta_twitter_site: "@hannahpixels"
  meta_twitter_creator: "@hannahpixels"


page_gen-dirs: true # uncomment, if you prefer to generate named folders

page_gen:
  - data: 'jobs'
    template: 'job'
    name: 'slug'
    dir: 'job'

  - data: 'jobs'
    template: 'company'
    name: 'company'
    dir: 'company'

  - data: 'jobs'
    template: 'role'
    name: 'role_slug'
    dir: 'role'


collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
